### ISSUE TITLE
To small browser window while test executing

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#10]
To small browser window while test executing. 
The browser opens by default in a small window, if the test must go through many elements that are not visible then element can not be found (is not clickable as not visible) and error occurs.

**Test to reproduce:**

Background: User access Activities page
  Given the user access the 'https://apex.oracle.com/pls/apex/dataconsulting/r/customers/login' url
  And user entered '{username}' in 'Username' field
  And user entered '{password}' in 'Password' field
  And user clicked on the 'Sign In' button

Scenario: Set IG Filter and verify record exists - Reports 
  When user navigates to 'Reports->All Customers' page
  Then at least one record can be found in 'Customers' IR by:
    | Customer      | Summary                                           | Category | Marquee Customer | Publicly Referenceable | Product Uses   | Status   | Geography | Industry       | Tags          | Web Site                  |
    | Barney Burger | Restuarant chain, rapidly spreading across Japan. | Consumer | No               | Yes                    | Symmetric 2000 | Customer | Japan     | Consumer Goods | CLOUD, MOBILE | http://www.barneyburger.j |

![browser to small](https://user-images.githubusercontent.com/113348992/197152145-409bef17-9abc-43fb-83da-325b8fd212b9.png)

**Expected Result:**

The browser opens in maximized window and framework is able to make page elements visible

**Comment by borowskikrz** [comment]
The problem reported has different couse and it will be fixed in seperate ticket. 
However, now it is possible to start the browser with maximize windows.
