### ISSUE TITLE
Framework goes through test to fast and error occurs

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#11]
Framework goes through test to fast and error occurs.

**Test to reproduce:**

Background: User access Activities page
  Given the user access the 'https://apex.oracle.com/pls/apex/dataconsulting/r/customers/login' url
  And user entered '{username}' in 'Username' field
  And user entered '{password}' in 'Password' field
  And user clicked on the 'Sign In' button

Scenario: Set IG Filter and verify record exists - Reports
  When user navigates to 'Reports->All Customers' page
  Then at least one record can be found in 'Customers' IR by:
    | Customer      | Summary                                           | Category | Marquee Customer | Publicly Referenceable | Product Uses   | Status   | Geography | Industry       | Tags          | Web Site                  |
    | Barney Burger | Restuarant chain, rapidly spreading across Japan. | Consumer | No               | Yes                    | Symmetric 2000 | Customer | Japan     | Consumer Goods | CLOUD, MOBILE | http://www.barneyburger.j |

![szybki komp](https://user-images.githubusercontent.com/113348992/197154752-b29197de-220c-42bf-8abe-3217a65bb4c1.png)

**Expected result:**

No error occurs.

**Comment by borowskikrz** [comment]
Already fixed while implementing other features
