### ISSUE TITLE
Framework starts test before browser displays page

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#12]
Framework starts test before browser displays page and error occurs.

**Test to reproduce:**

  Background: User access Activities page
    Given the user access the 'https://apex.oracle.com/pls/apex/f?p=59118' url
    And user entered '{username}' in 'username' field
    And user entered '{password}' in 'password' field
    And user clicked on the 'Sign In' button
    And waiting for 1 seconds
  
Scenario: Set Shuttle Box - Single
    When user moves values 'Option 2' in 'Shuttle Item' shuttle item
    And waiting for 1 seconds
    Then value 'Option 2' in 'Shuttle Item' shuttle item is chosen
    And user moves values 'Option 1' in 'Shuttle Item' shuttle item
    And waiting for 1 seconds
    Then value 'Option 1' in 'Shuttle Item' shuttle item is chosen
    And waiting for 1 seconds
    And user moves values 'Option 2' in 'Shuttle Item' shuttle item
    And waiting for 2 seconds

**Test without delay**

![ddd](https://user-images.githubusercontent.com/113348992/197158714-d407d2f1-8e2c-450c-b5fa-452e88aba32c.png)

**Test with delay (1 second)**

![vvvv](https://user-images.githubusercontent.com/113348992/197159293-566e8cd7-3066-42d1-9738-8c22990fab17.png)

**Expected result:**

Test should execute (without any delay) after browser displays webpage

**Comment by borowskikrz** [comment]
Already fixed while implementing other features.
