### ISSUE TITLE
Shuttle item selection replaces existing selection

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#13]
Shuttle item selection (replaces) overwrites existing selection
Rule _"user moves value(s) {listOfStrings} in {string} shuttle item"_ sets value(s) in shuttle item so existing selection is lost

**Test to reproduce:**

Background: User access Activities page
    Given the user access the 'https://apex.oracle.com/pls/apex/f?p=59118' url
    And user entered '{username}' in 'username' field
    And user entered '{password}' in 'password' field
    And user clicked on the 'Sign In' button
    And waiting for 1 seconds

Scenario: Set Shuttle Box - Single
  When user moves values 'Option 2' in 'Shuttle Item' shuttle item
  And waiting for 3 seconds
  Then value 'Option 2' in 'Shuttle Item' shuttle item is chosen
  And waiting for 3 seconds
  And user moves values 'Option 1' in 'Shuttle Item' shuttle item
  Then value 'Option 1' in 'Shuttle Item' shuttle item is chosen
  And waiting for 3 seconds

![obraz](https://user-images.githubusercontent.com/113348992/197162068-415fcc6c-0251-4b3e-968f-56d2e49d9a87.png)

![1](https://user-images.githubusercontent.com/113348992/197162702-d4cfed0e-e053-4b14-a327-5f57378fd8ec.png)

![2](https://user-images.githubusercontent.com/113348992/197162724-d68512fc-9cce-4a9f-887e-5de91847a673.png)

**Expected result:** 

Both items are selected in shuttle item

**Comment by borowskikrz** [comment]
Fixed in branch: https://github.com/dataconsulting-pl/APEX-Low-Test-Framework/tree/13-shuttle-item-selection-replaces-existing-selection
