### ISSUE TITLE
Not able to find button 'Download' on the Download pop-up

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#15]
Not able to find button 'Download' on the Download pop-up

**Test to reproduce:**

  Background:
    Given the user access the 'https://apex.oracle.com/pls/apex/r/dataconsulting/customers/login' url
    When user entered '{username}' in 'Username' field
    And user enters '{password}' in 'Password' field
    And user presses the 'Sign In' button

Scenario: Download on pop-up 
      When user navigates to 'Contacts' page
      And user clicked on the 'Actions' button
      And user presses the 'Download' button
      And user presses the 'Download' button on 'Download' pop-up
      And waiting for 3 seconds

![12](https://user-images.githubusercontent.com/113348992/201643255-816beec1-3bae-473a-a5f9-6abac89f3bcc.png)

**Expected result:**

Able to find button 'Download' on the Download pop-up

**Comment by borowskikrz** [comment]
The problem was actually with two buttons having the same name. Added new step where user can specify also class do distinguish buttons.
