### ISSUE TITLE
Not able to select button without text displayed in the form of icon

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#22]
Not able to select button without text displayed in the form of icon

**Steps to reproduce:**

  Background: User access Customers page
    Given the user access the 'https://apex.oracle.com/pls/apex/dataconsulting/r/customers/login' url
    And user entered '{username}' in 'Username' field
    And user entered '{password}' in 'Password' field
    And user clicked on the 'Sign In' button

  Scenario: Enter the text into text field
    Given user navigates to 'Contacts' page
    When user clicked on the 'Add Contact' button
    And frame 'Contact Details' is visible
    

![bb](https://user-images.githubusercontent.com/113348992/203272014-043df811-bfb1-4782-a8df-fdb8c66d7341.png)

**Expected result:**

Should able to select button without text displayed in the form of icon

**Comment by borowskikrz** [comment]
Steps to add text into popup lov element has been implemented. The button presented in the example is a part of the popup lov element. 
Please use newly written steps.
