### ISSUE TITLE
Shuttle item uses operator contains instead equals

### ISSUE THREAD

**Issue by OlaTrznadel** [dataconsulting-pl/APEX-Low-Test-Framework#32]
Chosen values::                     And user moves values 'cat, dog, mouse, parrot' in 'GES:' shuttle item
Checking of chosen values:    And values 'cat, dog, mouse' in 'GES:' shuttle item are chosen

The result of test is positive even if tested values are not entirely equal chosen values. It can leads to false positives test results.
Please implement in such way that result of the test is not positive until values aren't entirely the same.

**Comment by borowskikrz** [comment]
Corrected. Now it is verified if all expected option are selected and also if all option that were selected were also expected
