### ISSUE TITLE
Editing information in a text box

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#6]
While editing information in a text box condition ‘And user enters {string} in {string} field’ prepends new value to the existing one.

**Test to reproduce:**

  Background:
    Given the user access the 'https://apex.oracle.com/pls/apex/r/dataconsulting/customers/login' url
    When user entered '{username}' in 'Username' field
    And user enters '{password}' in 'Password' field
    And user presses the 'Sign In' button
    And user navigates to 'Customers' page
    Then verify, that menu option 'Customers' is selected

Rule: Add and edit new Customer
  Scenario: Add and edit new Customer
    Given user clicked on the 'Add Customer' button
    When user enters 'J Nowak' in 'Customer Name' field
    And user presses the 'Add Customer' button
    And user presses the 'Edit Customer' button
    And user enters 'K Nowak' in 'Customer Name' field
    And user presses the 'Apply Changes' button

![Editing Customers](https://user-images.githubusercontent.com/113348992/196940425-c80a9d2f-8ea4-469c-bcd7-8865fc79d7bf.png)

**Expected result:**
Should replace current value in a text box with one new.

**Comment by borowskikrz** [comment]
Fixed while implementing other features.
