### ISSUE TITLE
Not able to find an interactive grid button 

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#7]
Not able to find an interactive grid button 'Actions'

**Test to reproduce:**

Background:
  Given the user access the 'https://apex.oracle.com/pls/apex/r/dataconsulting/customers/login' url
  When user entered '{username}' in 'Username' field
  And user enters '{password}' in 'Password' field
  And user presses the 'Sign In' button
  And user navigates to 'Customers' page
  Then verify, that menu option 'Customers' is selected

Rule: Download Report
  Scenario: Download Report
    When user navigates to 'Contacts' page
    And user clicked on the 'Actions' button
    And user presses the 'Download' button

![Button_Actions_red](https://user-images.githubusercontent.com/113348992/197145520-97c08ac1-e9a2-4a5e-938b-26880b490ea0.png)

![Button Actions](https://user-images.githubusercontent.com/113348992/197145591-47ec0257-1528-454b-8a51-0b442e0e5546.png)

**Expected Result:** 

Be able to find and verify interactive grid buttons

**Comment by borowskikrz** [comment]
Fixed while implementing other features.
