### ISSUE TITLE
Not able to unset the same checkboxes that has been set 

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#9]
Not able to unset the same checkboxes that has been set.
When test sets few checkboxes and then tries to unset all those checkboxes error occurs.

**Test to reproduce:**

Background: User access Activities page
  Given the user access the 'https://apex.oracle.com/pls/apex/dataconsulting/r/customers/login' url
  And user entered '{username}' in 'Username' field
  And user entered '{password}' in 'Password' field
  And user clicked on the 'Sign In' button

Scenario: Set and unset Checkbox - List
  When user navigates to 'Customers' page
  And user presses the 'Add Customer' button
  When user sets checkbox 'Quote, Logo' for 'Reference Types' checkbox item
  And user unsets checkbox 'Quote, Logo' for 'Reference Types' checkbox item
  And waiting for 2 seconds

![Set_unset_function](https://user-images.githubusercontent.com/113348992/197149029-390a9d37-9bdd-424e-bb8b-336625ca9f19.png)

![set_unset_function1](https://user-images.githubusercontent.com/113348992/197149074-d8d33bbb-c6f5-455e-b6c4-f31856a731d9.png)

**Expected result:**

Error should not be thrown while unsetting previously set checkboxes.

**Comment by borowskikrz** [comment]
Issue has been fixed.
